modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
# A URL to query for updates for this mod. See the JSON tryComplete specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "${architectury_api_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="gamestages"
mandatory=true
versionRange="${gamestages_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ftbteams"
mandatory=true
versionRange="${ftbteams_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ftbquests"
mandatory=false
versionRange="${ftbquests_version_range}"
ordering="AFTER"
side="BOTH"